# Site settings
title: "Zahiir's Portfolio"
description: "A glimpse into my journey as a CS student and my projects in pen testing, web development, AI, and more!"
baseurl: "/"
url: "https://peerbux-muhammud-zahiir.github.io/"  
# Author settings
author:
  name: "Zahiir"
  email: "zahiir.cs@gmail.com" 
  linkedin: "https://www.linkedin.com/in/zahiir-peerbux-221621310/"  
  whatsapp: "https://wa.me/59100627" 

# Social links
social:
  github: "https://github.com/Peerbux-Muhammud-Zahiir"  
  linkedin: "https://www.linkedin.com/in/zahiir-peerbux-221621310/"  
  whatsapp: "https://wa.me/59100627" 

# Theme settings
theme: "hacker"

# Navigation links
nav_links:
  - title: "About Me"
    url: "/about"
  - title: "Coding"
    url: "/coding"
  - title: "Projects"
    url: "/projects"

# Projects
projects:
  - title: "Azure Cloud Challenge 2024"
    description: "Bagged 1st prize for the first time. Successfully created and deployed virtual networks, virtual machines, SQL server and SQL database, website using GitHub and integrated statistics using Azure Power BI."
    link: "https://github.com/Peerbux-Muhammud-Zahiir/cloud_challenge" 
  - title: "Bio-Tech Hackathon"
    description: "Led the Open Source Avengers to create NutriCare, an AI-driven mobile app using Flutter, Dart, Firebase, TensorFlow Lite, Nutritionix API, and Gemini API to recommend diet plans for all demographics in Mauritius. Trained a model on Teachable Machine using the Kaggle food dataset."
    link: "https://github.com/Peerbux-Muhammud-Zahiir/NutriCare_app"  
    images_link: "https://drive.google.com/drive/folders/1-XbjBCAY97GROMaVo4vlgykqoA9EF5ru"  

  - title: "Game of Code CTF"
    description: "My team, the Binary Coders, implemented a basic online learning platform to introduce Python language to children using HTML5, CSS3, and JS."
    link: "https://github.com/JoottunAtish/Game-of-code-CTF"  
    images_link: "https://drive.google.com/drive/folders/1ouvE1ZtAVX81vpPRs7Yjs-tx2YbOVlob"  

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional: SEO settings
seo:
  title: "Zahiir's Portfolio"
  description: "Explore my projects and journey as a CS student, including achievements in AI, web development, and more."
  keywords: "CS Student, Pen Testing, Web Development, AI, GitHub Pages"
  twitter:
    username: "ZahiirPeerbux"  # Replace with your Twitter handle if you have one

# Optional: Footer settings
footer:
  copyright: "© 2024 Zahiir. All rights reserved."
